#!/bin/bash
alias BEGINCOMMENT="if [ ]; then"
alias ENDCOMMENT="fi"
cwd=$(pwd)

args=("$@")
#echo arguments to the shell



rm -r -f libraries
mkdir -p libraries
mkdir -p sysroot-x86
mkdir -p sysroot-arm

git clone https://github.com/gflags/gflags.git ./libraries/gflags
git clone https://github.com/google/glog.git ./libraries/glog
git clone https://github.com/leethomason/tinyxml2.git ./libraries/tinyxml2
git clone https://github.com/google/googletest.git ./libraries/googletest

cd $cwd/toolchain
tar -xf gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux.tar.xz
cd $cwd


cd build-x86
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=toolchain-x86.cmake ..
make 
make install

#now rebuild again (will find gflags this time)
cmake ..
make


cd build-arm
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=toolchain-arm.cmake ..
make
make install


#now rebuild again (will find gflags this time)
cmake ..
make

